export const FETCH_TYPEOPTIONS_SUCCESS = 'FETCH_TYPEOPTIONS_SUCCESS';
export const FETCH_SECTOROPTIONS_SUCCESS = 'FETCH_SECTOROPTIONS_SUCCESS';
export const FETCH_SEGMENTOPTIONS_SUCCESS = 'FETCH_SEGMENTOPTIONS_SUCCESS';
export const FETCH_COUNTRYGROUPOPTIONS_SUCCESS = 'FETCH_COUNTRYGROUPOPTIONS_SUCCESS';
export const FETCH_COUNTRYOPTIONS_SUCCESS = 'FETCH_COUNTRYOPTIONS_SUCCESS';
export const SEARCH_CLIENTS_SUCCESS = 'SEARCH_CLIENTS_SUCCESS';
export const SAVE_CLIENTS_SUCCESS = 'SAVE_CLIENTS_SUCCESS';
export const COMPARE_CLIENTS_SUCCESS = 'COMPARE_CLIENTS_SUCCESS';
